version: "3"

services:
  apache:
    build: # инструкции для создания образа
      # контекст (путь к каталогу, содержащему Dockerfile)
      context: ./bin/php8
    container_name: apache
    restart: "always"
    ports:
      - "81:80"
    # Cвязываем контейнеры вместе
    links:
      - database
    volumes:
      #  Монтируем директорию с php-скриптом внутрь контейнера
      - ./www:/var/www/html
      #  Монтируем файл конфигурации php.ini внутрь контейнера
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      #  Монтируем файл конфигурации Apache2 внутрь контейнерa
      - ./config/vhosts/apache2.conf:/etc/apache2/apache2.conf
      - ./config/vhosts/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      # Монтируем файл конфигурации портов
      - ./config/vhosts/ports.conf:/etc/apache2/ports.conf
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}

  database:
    build:
      context: "./bin/mysql8"
    container_name: mysql8
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - ./config/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    container_name: PMA
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: tiger
      MYSQL_ROOT_PASSWORD: tiger
#      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    volumes:
 #     - ./config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
      - ./config/pma/apache2.conf:/etc/apache2/apache2.conf

  nginx:
    build:
      context: "./bin/nginx/"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./www:/var/www/html
    depends_on:
      - apache

  redis:
    container_name: redis
    build:
      context: "./bin/redis/"
    command: redis-server /usr/local/etc/redis.conf
    ports:
      - "6379:6379"
    volumes:
     - ./logs/redis/redis.log:/usr/local/redis/redis.log
     - ./data/redis:/usr/local/redis/data
     - ./config/redis/redis.conf:/usr/local/etc/redis.conf
    restart: always

  composer:
    image: composer:latest
    volumes:
      - ./www/public/composer:/app
    working_dir: /app
    command:
      - install
    depends_on:
      - apache






